all: blinky

CONTIKI=../../..

### TARGET DECLARATION
TARGET = hiveMote
CPU_FAMILY = cc26xx
# CPU_FAMILY = cc13xx

### Toggle LED using button? Uncomment the following.
# CFLAGS += -DBLINK_USING_BUTTON

include $(CONTIKI)/Makefile.include