all: motor

CONTIKI=../../..

### TARGET DECLARATION
TARGET = hiveMote
CPU_FAMILY = cc26xx
# CPU_FAMILY = cc13xx

### Arduino Shield being used
SHIELD = SEEED_MOTOR_BOARD_V2

include $(CONTIKI)/Makefile.include
